Enforce wehe envelope
m-lab/k8s-support pull request #489
Opened 2020-09-09 20:28 UTC by stephen-soltesz

This change updates the wehe envelope configuration to enforce access tokens.

2020-09-09 20:33 UTC, nkinkade requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/489)* status: 0 of 1 LGTMs obtained

___
*[k8s/daemonsets/experiments/wehe.jsonnet, line 45 at r1](https://reviewable.io/reviews/m-lab/k8s-support/489#-MGoZOcyBxmQxCsrP-tp:-MGoZOcyBxmQxCsrP-tq:b4nv9n2) ([raw file](https://github.com/m-lab/k8s-support/blob/91a34e2a1194d06c674775e78953ec4b609a02d6/k8s/daemonsets/experiments/wehe.jsonnet#L45)):*
> ```Jsonnet
>               '-envelope.device=net1',
>               '-envelope.subject=wehe',
>               '-envelope.machine=$(MLAB_NODE_NAME)',
> ```

You're using `$(MLAB_NODE_NAME)` here, but no `env` variable with that name is configured for this container. Is this an oversight? Or maybe I'm not understanding how that variable is evaluated?

```
            env: [
              {
                name: 'MLAB_NODE_NAME',
                valueFrom: {
                  fieldRef: {
                    fieldPath: 'spec.nodeName',
                  },
                },
              },
            ],
```


<!-- Sent from Reviewable.io -->

2020-09-09 20:36 UTC, stephen-soltesz reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/489)* status: 0 of 1 LGTMs obtained

___
*[k8s/daemonsets/experiments/wehe.jsonnet, line 45 at r1](https://reviewable.io/reviews/m-lab/k8s-support/489#-MGoZOcyBxmQxCsrP-tp:-MGo_E-i9TnDxzIhSJjK:b-vu2fsv) ([raw file](https://github.com/m-lab/k8s-support/blob/91a34e2a1194d06c674775e78953ec4b609a02d6/k8s/daemonsets/experiments/wehe.jsonnet#L45)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

You're using `$(MLAB_NODE_NAME)` here, but no `env` variable with that name is configured for this container. Is this an oversight? Or maybe I'm not understanding how that variable is evaluated?

```
            env: [
              {
                name: 'MLAB_NODE_NAME',
                valueFrom: {
                  fieldRef: {
                    fieldPath: 'spec.nodeName',
                  },
                },
              },
            ],
```
</blockquote></details>

Great catch. I totally missed it. Fixed.


<!-- Sent from Reviewable.io -->

2020-09-09 20:38 UTC, nkinkade approved these changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/489)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-09-09 22:53 UTC, stephen-soltesz commented
I've merged https://github.com/m-lab/epoxy-images/pull/189 so staging should have updated images soon. I've manually run modprobe on all mlab4 nodes in preparation for merging this change.

Before deploying the wehe config to production, the ip6table-filter module needs to be available for the access envelope to wai.

2020-09-09 22:54 UTC, merged

2021-02-19 18:52 UTC, stephen-soltesz commented
Part of https://github.com/m-lab/k8s-support/issues/560