Update systemd flag and use latest static version
m-lab/k8s-support pull request #551
Opened 2021-02-08 15:24 UTC by stephen-soltesz

The unpinned version led to an uncontrolled deployment of the latest node exporter version, which included changes to flags.

This change pins the version and updates the flag.

```
panic: Couldn't create metrics handler: couldn't create collector: --collector.systemd.unit-whitelist and --collector.systemd.unit-include are mutually exclusive
goroutine 1 [running]:
main.newHandler(0xc000218f01, 0x28, 0xd0cf40, 0xc0002bd200, 0x0)
	/app/node_exporter.go:64 +0x317
main.main()
	/app/node_exporter.go:184 +0x1052
```

2021-02-08 16:41 UTC, stephen-soltesz commented
related to https://github.com/m-lab/k8s-support/issues/502

2021-02-08 18:07 UTC, nkinkade requested changes
Since the systemd collector is not working on virtual nodes due to AppArmor policies, perhaps we should add:

```
nodeSelector:
  'mlab/type': 'physical'
```

... to the DaemonSet to resolve https://github.com/m-lab/k8s-support/issues/502? I believe the primary motivation for enabling the systemd collector in the first place was to be able to monitor the `setup-after-boot.service` and any other services which might be critical to measurements (like the `configure-tc-fq.service`). I'm not sure we need this on the API nodes.

Also, we should add some sort of alert for these. [The systemd collector was enabled quite some time ago, but no alerts were ever configured to take advantage of it](https://github.com/m-lab/k8s-support/issues/502#issuecomment-758314121).

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/551#-:-MT1magz3oob8YPsXMJP:b17fwiw)* status: 0 of 1 LGTMs obtained

___
*[k8s/daemonsets/core/node-exporter.jsonnet, line 36 at r1](https://reviewable.io/reviews/m-lab/k8s-support/551#-MT1lj4xBnUcmr413eK0:-MT1lj4xBnUcmr413eK1:bojntyf) ([raw file](https://github.com/m-lab/k8s-support/blob/e85644ec51d135e9472d0656f548b3156745cf3e/k8s/daemonsets/core/node-exporter.jsonnet#L36)):*
> ```Jsonnet
>               '--collector.netstat.fields=^(.*_(InErrors|InErrs)|Ip_Forwarding|Ip(6|Ext)_(InOctets|OutOctets)|Icmp6?_(InMsgs|OutMsgs)|TcpExt_(TCPDSACK.*|Listen.*|Syncookies.*|TCPSynRetrans)|Tcp_(ActiveOpens|InSegs|OutSegs|PassiveOpens|RetransSegs|CurrEstab)|Udp6?_(InDatagrams|OutDatagrams|NoPorts))$',
>               '--collector.systemd',
>               '--collector.systemd.unit-include=^(setup-after-boot.service|system-cloudinit.+|docker.service|kubelet.service)',
> ```

Would you also add `containerd.service` and `configure-tc-fq.service` to this list? Also,  I can't find any units on nodes or API machines that look like `system-cloudinit.*`, so maybe we can safely remove that one (maybe a vestigial CoreOS thing).


<!-- Sent from Reviewable.io -->

2021-02-09 17:48 UTC, stephen-soltesz reviewed
PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/551#-:-MT6u3a-CbuANXn1QRC_:b-833305)* status: 0 of 1 LGTMs obtained

___
*[k8s/daemonsets/core/node-exporter.jsonnet, line 36 at r1](https://reviewable.io/reviews/m-lab/k8s-support/551#-MT1lj4xBnUcmr413eK0:-MT6u2Jx469nIGEyj-KP:b-896fix) ([raw file](https://github.com/m-lab/k8s-support/blob/e85644ec51d135e9472d0656f548b3156745cf3e/k8s/daemonsets/core/node-exporter.jsonnet#L36)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Would you also add `containerd.service` and `configure-tc-fq.service` to this list? Also,  I can't find any units on nodes or API machines that look like `system-cloudinit.*`, so maybe we can safely remove that one (maybe a vestigial CoreOS thing).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-09 18:38 UTC, nkinkade approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/551)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-02-09 19:36 UTC, merged